//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceWeb.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceWeb.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string AllDepartments_Name {
            get {
                return ResourceManager.GetString("AllDepartments_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оклад.
        /// </summary>
        public static string AllDepartments_Salary {
            get {
                return ResourceManager.GetString("AllDepartments_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальность.
        /// </summary>
        public static string AllDepartments_Specification {
            get {
                return ResourceManager.GetString("AllDepartments_Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string AllDepartments_Surname {
            get {
                return ResourceManager.GetString("AllDepartments_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карты банков.
        /// </summary>
        public static string Banks_Card {
            get {
                return ResourceManager.GetString("Banks_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СОЗДАНИЕ КАРТЫ.
        /// </summary>
        public static string Banks_CreatCard {
            get {
                return ResourceManager.GetString("Banks_CreatCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моцная картаy.
        /// </summary>
        public static string Banks_MocCard {
            get {
                return ResourceManager.GetString("Banks_MocCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта покупо.
        /// </summary>
        public static string Banks_ShoppCard {
            get {
                return ResourceManager.GetString("Banks_ShoppCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод.
        /// </summary>
        public static string Banks_Transfer {
            get {
                return ResourceManager.GetString("Banks_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Х карта.
        /// </summary>
        public static string Banks_XCard {
            get {
                return ResourceManager.GetString("Banks_XCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лаборатория.
        ///   Ищет локализованную строку, похожую на Банк.
        /// </summary>
        public static string DepartmentType_Bank {
            get {
                return ResourceManager.GetString("DepartmentType_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лаборатория.
        /// </summary>
        public static string DepartmentType_Laboratory {
            get {
                return ResourceManager.GetString("DepartmentType_Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производство.
        /// </summary>
        public static string DepartmentType_Manufactory {
            get {
                return ResourceManager.GetString("DepartmentType_Manufactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центр управления полетами.
        /// </summary>
        public static string DepartmentType_MissionControlCenter {
            get {
                return ResourceManager.GetString("DepartmentType_MissionControlCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        public static string DepartmentType_Other {
            get {
                return ResourceManager.GetString("DepartmentType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Космонавт.
        /// </summary>
        public static string DepartmentType_SpacecraftCrew {
            get {
                return ResourceManager.GetString("DepartmentType_SpacecraftCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестно.
        /// </summary>
        public static string DepartmentType_Unknown {
            get {
                return ResourceManager.GetString("DepartmentType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работает.
        /// </summary>
        public static string EmployeStatus_Accepted {
            get {
                return ResourceManager.GetString("EmployeStatus_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не принят.
        /// </summary>
        public static string EmployeStatus_Denied {
            get {
                return ResourceManager.GetString("EmployeStatus_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уволен.
        /// </summary>
        public static string EmployeStatus_Fired {
            get {
                return ResourceManager.GetString("EmployeStatus_Fired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка на работу.
        /// </summary>
        public static string EmployeStatus_Request {
            get {
                return ResourceManager.GetString("EmployeStatus_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос ответ.
        /// </summary>
        public static string HomeIndex_FAQ {
            get {
                return ResourceManager.GetString("HomeIndex_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый текст.
        /// </summary>
        public static string HomeIndex_NewText {
            get {
                return ResourceManager.GetString("HomeIndex_NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ракетчики.
        /// </summary>
        public static string HomeIndex_Rocket {
            get {
                return ResourceManager.GetString("HomeIndex_Rocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банкиры.
        /// </summary>
        public static string HomeIndex_RocketBank {
            get {
                return ResourceManager.GetString("HomeIndex_RocketBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Layout_Exit {
            get {
                return ResourceManager.GetString("Layout_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Layout_Login {
            get {
                return ResourceManager.GetString("Layout_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Layout_Password {
            get {
                return ResourceManager.GetString("Layout_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Layout_Registration {
            get {
                return ResourceManager.GetString("Layout_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банк.
        /// </summary>
        public static string LayoutBank_logoNameBank {
            get {
                return ResourceManager.GetString("LayoutBank_logoNameBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рокеты.
        /// </summary>
        public static string LayoutBank_logoNameRocket {
            get {
                return ResourceManager.GetString("LayoutBank_logoNameRocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глава отдела.
        /// </summary>
        public static string Positin_Leader {
            get {
                return ResourceManager.GetString("Positin_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заместитель.
        /// </summary>
        public static string Position_Deputy {
            get {
                return ResourceManager.GetString("Position_Deputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер.
        /// </summary>
        public static string Position_Manager {
            get {
                return ResourceManager.GetString("Position_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессиональный рабочий.
        /// </summary>
        public static string Position_ProfessionalWorker {
            get {
                return ResourceManager.GetString("Position_ProfessionalWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стажер.
        /// </summary>
        public static string Position_Trainee {
            get {
                return ResourceManager.GetString("Position_Trainee", resourceCulture);
            }
        }
    }
}
