//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceWeb.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceWeb.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос ответ.
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string AllDepartments_Name {
            get {
                return ResourceManager.GetString("AllDepartments_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оклад.
        /// </summary>
        public static string AllDepartments_Salary {
            get {
                return ResourceManager.GetString("AllDepartments_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Специальность.
        /// </summary>
        public static string AllDepartments_Specification {
            get {
                return ResourceManager.GetString("AllDepartments_Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string AllDepartments_Surname {
            get {
                return ResourceManager.GetString("AllDepartments_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лаборатория.
        /// </summary>
        public static string DepartmentType_Laboratory {
            get {
                return ResourceManager.GetString("DepartmentType_Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производство.
        /// </summary>
        public static string DepartmentType_Manufactory {
            get {
                return ResourceManager.GetString("DepartmentType_Manufactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Центр управления полетами.
        /// </summary>
        public static string DepartmentType_MissionControlCenter {
            get {
                return ResourceManager.GetString("DepartmentType_MissionControlCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другое.
        /// </summary>
        public static string DepartmentType_Other {
            get {
                return ResourceManager.GetString("DepartmentType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Космонавт.
        /// </summary>
        public static string DepartmentType_SpacecraftCrew {
            get {
                return ResourceManager.GetString("DepartmentType_SpacecraftCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестно.
        /// </summary>
        public static string DepartmentType_Unknown {
            get {
                return ResourceManager.GetString("DepartmentType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос ответ.
        /// </summary>
        public static string HomeIndex_FAQ {
            get {
                return ResourceManager.GetString("HomeIndex_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый текст.
        /// </summary>
        public static string HomeIndex_NewText {
            get {
                return ResourceManager.GetString("HomeIndex_NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ракетчики.
        /// </summary>
        public static string HomeIndex_Rocket {
            get {
                return ResourceManager.GetString("HomeIndex_Rocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банкиры.
        /// </summary>
        public static string HomeIndex_RocketBank {
            get {
                return ResourceManager.GetString("HomeIndex_RocketBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Layout_Exit {
            get {
                return ResourceManager.GetString("Layout_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Layout_Login {
            get {
                return ResourceManager.GetString("Layout_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Layout_Password {
            get {
                return ResourceManager.GetString("Layout_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Layout_Registration {
            get {
                return ResourceManager.GetString("Layout_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заведующий отделением.
        /// </summary>
        public static string Specification_Leader {
            get {
                return ResourceManager.GetString("Specification_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другое.
        /// </summary>
        public static string Specification_Other {
            get {
                return ResourceManager.GetString("Specification_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ученый.
        /// </summary>
        public static string Specification_Scientist {
            get {
                return ResourceManager.GetString("Specification_Scientist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Космонавт.
        /// </summary>
        public static string Specification_Spacemen {
            get {
                return ResourceManager.GetString("Specification_Spacemen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техник.
        /// </summary>
        public static string Specification_Technicist {
            get {
                return ResourceManager.GetString("Specification_Technicist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не назанчено.
        /// </summary>
        public static string Specification_Unknow {
            get {
                return ResourceManager.GetString("Specification_Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инженер.
        /// </summary>
        public static string Specification_Еngineer {
            get {
                return ResourceManager.GetString("Specification_Еngineer", resourceCulture);
            }
        }
    }
}
